### ISSUE TITLE
Fallbacks for Blank Config Options

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq#155]
**Is your feature request related to a problem? Please describe.**
Config.get() fallbacks only seem to output for missing options, not blank ones

```
config.get('options', 'blank', fallback='fall') #Returns ""
config.get('options', 'missing', fallback='fall') #Returns "fall"
```

**Describe the solution you'd like**
Blank config options to return the fallback value.

**Comment by mlaferrera** [comment]
This is expected behavior for the ConfigParser library. Options can be blank, so defaulting to a fallback is not a good idea if the option is defined and simply blank. If you would like it to default to fallback, the value must either be missing, or set to `None`

**Comment by Kolano** [comment]
Setting the value to None doesn't seem to work out.

I have this in my .stoq file...
```
restart_file = None
```

And this code still outputs "None"...
```
config.get('options', 'restart_file', fallback=datetime.fromtimestamp(0,timezone.utc))
```

**Comment by mlaferrera** [comment]
The value needs to be literal `None` type object in python, not the string None. If you want a default value, either comment the option out in the config file, or set it to a default value you would like it to be.

**Comment by Kolano** [comment]
Sorry this is still confusing and not seeming to work out. With options commented out I get...

```
Traceback (most recent call last):
  File "/home/pass/.stoq/.venv/lib/python3.8/site-packages/stoq/core.py", line 812, in _resolve_plugin_dependencies
    plugin: WorkerPlugin = self.load_plugin(plugin_name)  # type: ignore
  File "/home/pass/.stoq/.venv/lib/python3.8/site-packages/stoq/plugin_manager.py", line 177, in load_plugin
    plugin = plugin_class(plugin_config)
  File "/home/pass/.stoq/plugins/pass-opswat/pass-opswat.py", line 76, in __init__
    self.restart_hash = datetime.fromisoformat(config.get('options', 'restart_hash'), fallback=datetime.fromtimestamp(0,timezone.utc))
  File "/usr/lib/python3.8/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'restart_hash' in section: 'options'
```

The only thing I can get to work is to leave them blank and separately check for such not relying on the fallback values...
```
			if config.get('options', 'restart_hash') != "":
				self.restart_hash = datetime.fromisoformat(config.get('options', 'restart_hash'))
			else:
				self.restart_hash = datetime.fromtimestamp(0,timezone.utc)
```

**Comment by mlaferrera** [comment]
No problem, I'll try to clarify for you. Please let me know if this doesn't make sense.

stoQ leverages the python library [configparser](https://docs.python.org/3.7/library/configparser.html). When using `config.get`, you'll want to define a `fallback` value, otherwise you will get the above `Exception` of `configparser.NoOptionError`. 

To keep it straightforward, below are some examples of the regular `configparser` usage, completely independent of stoQ.

Let's start with a missing configuration options with no fallback. If the configuration option is not present/commented out, `config.get()` will raise an `Exception` because the configuration option does not exist:

```
>>> from configparser import ConfigParser
>>> config = ConfigParser()
>>> config.get('options', 'restart_hash')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'options'
```

However, if you add a `fallback` argument and provide a value, `config.get()` will return that value if the configuration option does not exist, avoiding the `Exception` altogether:
```
>>> from configparser import ConfigParser
>>> from datetime import datetime, timezone
>>> config = ConfigParser()
>>> config.get('options', 'restart_hash', fallback=datetime.fromtimestamp(0,timezone.utc))
datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)
```
I hope this clarifies everything for you. If not, please feel free to share your code and I can help you walk through getting the configuration options to work.
